//! HMAC-SHA256 append-only audit log (FR-104, NFR-204).
//!
//! ## Design
//!
//! Every audit entry is part of a cryptographic chain: each entry includes the
//! HMAC of the previous entry (`prev_hmac`), binding the log into a tamper-evident
//! sequence. A single background thread owns the file handle and HMAC state,
//! serialising all writes and ensuring no entry is ever skipped or reordered.
//!
//! ### Write path (per tool call)
//!
//! 1. Caller constructs an `EntryRequest` with all fields and a `oneshot::Sender`.
//! 2. Entry is sent to the background writer via an unbounded channel.
//! 3. Background thread serialises, computes HMAC, writes, and calls `sync_all()`.
//! 4. Background thread sends `Ok(())` back through the oneshot.
//! 5. Caller blocks (`blocking_recv`) until fsync is confirmed — satisfying
//!    NFR-204: "MCP forward blocked until local audit entry durably written".
//! 6. After confirmation, SIEM export is attempted (async, within timeout).
//!
//! ### SIEM export
//!
//! After fsync confirmation the logger calls `siem::try_export`, which races the
//! HTTP request against the configured SIEM timeout (default 2 s). A failed or
//! timed-out export emits `siem_export_failed` to structured stderr but does not
//! block or fail the tool call — the local log is the durable fallback.

use chrono::Utc;
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::Sha256;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Arc;
use tokio::sync::{mpsc, oneshot};

use super::siem::{SiemExporter, try_export};

type HmacSha256 = Hmac<Sha256>;

/// Sentinel value for the first entry's `prev_hmac` field.
pub const ZERO_HMAC: &str =
    "0000000000000000000000000000000000000000000000000000000000000000";

// ─── Schema ────────────────────────────────────────────────────────────────

/// A single entry in the append-only audit log.
///
/// Every field maps 1-to-1 with the PRD §5.4 structured log schema.
/// Fields marked `skip_serializing_if = "Option::is_none"` are omitted from
/// the JSON line when absent, keeping the log compact.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditEntry {
    /// RFC-3339 timestamp at write time.
    pub ts: String,
    /// Session UUID generated by the gateway (never supplied by the agent).
    pub session_id: String,
    /// Event name (e.g. `tool_allow`, `tool_deny`, `siem_export_failed`).
    pub event: String,
    /// Tool name from the MCP `tools/call` request, if applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
    /// SHA-256 hex of the canonical JSON of the tool arguments.
    /// Raw params are never stored by default (see `--include-params`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params_hash: Option<String>,
    /// Raw params — only present when `include_params = true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<Value>,
    /// Human-readable denial or event reason.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Policy evaluation latency in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<f64>,
    /// OIDC `sub` claim — cryptographic identity of the session owner.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_sub: Option<String>,
    /// OIDC `email` claim — human-readable identity for SIEM searches.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_email: Option<String>,
    /// SHA-256 hash of the active policy file at event time.
    /// Enables CISOs to correlate events against policy versions in the SIEM.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policy_hash: Option<String>,
    /// Client remote IP address (FR-201).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_ip: Option<String>,
    /// Zero-based position of this entry within the current log file.
    pub entry_index: u64,
    /// HMAC hex of the previous entry (ZERO_HMAC for the first entry).
    pub prev_hmac: String,
    /// HMAC-SHA256 of this entry's canonical JSON (with `hmac` field set to None).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hmac: Option<String>,
}

// ─── Write request ─────────────────────────────────────────────────────────

/// A request sent from the public API to the background writer thread.
struct EntryRequest {
    session_id:     String,
    event:          String,
    tool_name:      String,
    params_hash:    Option<String>,
    params:         Option<Value>,
    reason:         Option<String>,
    latency_ms:     Option<f64>,
    identity_sub:   Option<String>,
    identity_email: Option<String>,
    policy_hash:    Option<String>,
    request_ip:     Option<String>,
    /// Oneshot sender through which the writer confirms fsync completion.
    ack:            oneshot::Sender<Result<AuditEntry, String>>,
}

// ─── Configuration ─────────────────────────────────────────────────────────

/// Configuration passed to `AuditLogger::new`.
pub struct AuditLoggerConfig {
    /// Path to the append-only log file.
    pub log_path:      PathBuf,
    /// Session UUID for this gateway instance.
    pub session_id:    String,
    /// Per-session HMAC secret (32 random bytes generated at startup).
    pub session_secret: Vec<u8>,
    /// Rotate the log file after this many bytes (0 = never).
    pub max_bytes:     u64,
    /// SIEM exporter — set to `Local` backend to disable network export.
    pub siem_exporter: Option<SiemExporter>,
    /// When true, raw params are stored alongside `params_hash`.
    pub include_params: bool,
}

// ─── Logger ────────────────────────────────────────────────────────────────

pub struct AuditLogger {
    sender:      mpsc::UnboundedSender<EntryRequest>,
    is_broken:   Arc<AtomicBool>,
    entry_count: Arc<AtomicU64>,
}

#[derive(Debug)]
pub enum AuditError {
    IoError(std::io::Error),
    SerializationError(String),
    WriterDead,
}

impl std::fmt::Display for AuditError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::IoError(e)              => write!(f, "I/O error: {}", e),
            Self::SerializationError(e)   => write!(f, "Serialization error: {}", e),
            Self::WriterDead              => write!(f, "Audit writer thread has terminated"),
        }
    }
}

impl AuditLogger {
    /// Construct a new logger and spawn its background writer thread.
    ///
    /// The writer thread owns the file handle and HMAC chain state.  It exits
    /// when the sender half of the channel is dropped (i.e. when `AuditLogger`
    /// is dropped), flushing any pending writes first.
    pub fn new(cfg: AuditLoggerConfig) -> Result<Self, AuditError> {
        let (tx, mut rx) = mpsc::unbounded_channel::<EntryRequest>();
        let is_broken      = Arc::new(AtomicBool::new(false));
        let is_broken_w    = is_broken.clone();
        let entry_count    = Arc::new(AtomicU64::new(0));
        let entry_count_w  = entry_count.clone();

        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&cfg.log_path)
            .map_err(AuditError::IoError)?;

        // Move config values into the writer thread.
        let log_path       = cfg.log_path.clone();
        let session_secret = cfg.session_secret.clone();
        let max_bytes      = cfg.max_bytes;
        let siem_exporter  = cfg.siem_exporter.clone();
        let include_params = cfg.include_params;

        // Tokio's `spawn_blocking` keeps the blocking writes off the async executor.
        // We use a dedicated OS thread via `std::thread::spawn` to avoid holding
        // a blocking-thread permit indefinitely.
        std::thread::spawn(move || {
            // Build a minimal single-thread Tokio runtime for the async SIEM call.
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("audit writer runtime");

            let mut current_idx: u64 = 0;
            let mut prev_hmac = ZERO_HMAC.to_string();

            while let Some(req) = rx.blocking_recv() {
                // ── Build the canonical entry (hmac = None) ────────────────
                let params_hash_field = req.params_hash.clone();
                let params_field      = if include_params { req.params.clone() } else { None };

                let mut entry = AuditEntry {
                    ts:             Utc::now().to_rfc3339(),
                    session_id:     req.session_id.clone(),
                    event:          req.event.clone(),
                    tool_name:      if req.tool_name.is_empty() { None } else { Some(req.tool_name.clone()) },
                    params_hash:    params_hash_field,
                    params:         params_field,
                    reason:         req.reason,
                    latency_ms:     req.latency_ms,
                    identity_sub:   req.identity_sub,
                    identity_email: req.identity_email,
                    policy_hash:    req.policy_hash,
                    request_ip:     req.request_ip,
                    entry_index:    current_idx,
                    prev_hmac:      prev_hmac.clone(),
                    hmac:           None,
                };

                // ── Compute HMAC over canonical JSON ────────────────────────
                let canonical = match serde_json::to_string(&entry) {
                    Ok(s)  => s,
                    Err(e) => {
                        let _ = req.ack.send(Err(format!("serialize error: {}", e)));
                        continue;
                    }
                };

                let mut mac = HmacSha256::new_from_slice(&session_secret)
                    .expect("HMAC key length is valid");
                mac.update(canonical.as_bytes());
                let hmac_hex = hex::encode(mac.finalize().into_bytes());
                entry.hmac = Some(hmac_hex.clone());

                // ── Write line + fsync ───────────────────────────────────────
                let line = match serde_json::to_string(&entry) {
                    Ok(l)  => l,
                    Err(e) => {
                        let _ = req.ack.send(Err(format!("final serialize error: {}", e)));
                        continue;
                    }
                };

                let write_ok = writeln!(file, "{}", line).is_ok()
                    && file.flush().is_ok()
                    && file.sync_all().is_ok();

                if !write_ok {
                    is_broken_w.store(true, Ordering::Relaxed);
                    let _ = req.ack.send(Err("disk write / fsync failed".to_string()));
                    break;
                }

                // ── Confirm fsync to caller via oneshot ──────────────────────
                let confirmed_entry = entry.clone();
                let _ = req.ack.send(Ok(confirmed_entry.clone()));

                // ── Update chain state ───────────────────────────────────────
                prev_hmac = hmac_hex.clone();

                // ── SIEM export (async, within timeout) ─────────────────────
                if let Some(ref exporter) = siem_exporter {
                    let exporter_clone = exporter.clone();
                    let entry_clone    = confirmed_entry.clone();
                    rt.block_on(async move {
                        try_export(&exporter_clone, &entry_clone).await;
                    });
                }

                // ── Log rotation ─────────────────────────────────────────────
                let needs_rotation = max_bytes > 0
                    && file.metadata().map(|m| m.len() >= max_bytes).unwrap_or(false);

                if needs_rotation {
                    let ts_compact  = Utc::now().format("%Y%m%dT%H%M%S%.9f").to_string();
                    let rand_suffix: u16 = rand::random();
                    let mut backup_path = log_path.clone();
                    backup_path.set_file_name(format!(
                        "{}.{}_{:04x}.bak",
                        log_path.file_name().unwrap().to_string_lossy(),
                        ts_compact,
                        rand_suffix,
                    ));

                    drop(file);

                    // Retry rename up to 10 times (Windows may hold file locks briefly).
                    let mut rename_ok = std::fs::rename(&log_path, &backup_path).is_ok();
                    if !rename_ok {
                        for _ in 0..10 {
                            std::thread::sleep(std::time::Duration::from_millis(50));
                            rename_ok = std::fs::rename(&log_path, &backup_path).is_ok();
                            if rename_ok { break; }
                        }
                    }

                    if !rename_ok {
                        is_broken_w.store(true, Ordering::Relaxed);
                        break;
                    }

                    match OpenOptions::new().create(true).append(true).open(&log_path) {
                        Ok(new_file) => {
                            file = new_file;

                            // Write a rotation-seed entry that carries the HMAC of the
                            // last entry in the old file, preserving chain continuity.
                            let mut seed = AuditEntry {
                                ts:             Utc::now().to_rfc3339(),
                                session_id:     req.session_id.clone(),
                                event:          "log_rotation_seed".to_string(),
                                tool_name:      None,
                                params_hash:    None,
                                params:         None,
                                reason:         None,
                                latency_ms:     None,
                                identity_sub:   None,
                                identity_email: None,
                                policy_hash:    None,
                                request_ip:     None,
                                entry_index:    0,
                                prev_hmac:      hmac_hex.clone(),
                                hmac:           None,
                            };

                            let seed_canonical = serde_json::to_string(&seed).unwrap();
                            let mut mac = HmacSha256::new_from_slice(&session_secret)
                                .expect("HMAC key");
                            mac.update(seed_canonical.as_bytes());
                            let seed_hmac = hex::encode(mac.finalize().into_bytes());
                            seed.hmac = Some(seed_hmac.clone());

                            let seed_line = serde_json::to_string(&seed).unwrap();
                            if writeln!(file, "{}", seed_line).is_err()
                                || file.flush().is_err()
                                || file.sync_all().is_err()
                            {
                                is_broken_w.store(true, Ordering::Relaxed);
                                break;
                            }

                            crate::logging::log_event(
                                crate::logging::Level::Info,
                                "log_rotated",
                                serde_json::json!({
                                    "archived": backup_path.to_string_lossy(),
                                    "new_log":  log_path.to_string_lossy(),
                                }),
                            );

                            prev_hmac   = seed_hmac;
                            current_idx = 1;
                        }
                        Err(_) => {
                            is_broken_w.store(true, Ordering::Relaxed);
                            break;
                        }
                    }
                } else {
                    current_idx += 1;
                }

                entry_count_w.store(current_idx, Ordering::Relaxed);
            }
        });

        Ok(Self {
            sender: tx,
            is_broken,
            entry_count,
        })
    }

    /// Write an audit entry and block until the local fsync is confirmed.
    ///
    /// Returns `Err` if:
    /// - The logger is in a broken state (prior disk error).
    /// - The background writer thread has terminated.
    /// - The fsync itself failed.
    ///
    /// On `Err` the caller **must** treat the event as a DENY (NFR-204).
    #[allow(clippy::too_many_arguments)]
    pub fn write_entry(
        &self,
        session_id:     &str,
        event:          &str,
        tool_name:      &str,
        params:         Option<Value>,
        reason:         Option<String>,
        latency_ms:     Option<f64>,
        identity_sub:   Option<String>,
        identity_email: Option<String>,
        policy_hash:    Option<String>,
        request_ip:     Option<String>,
    ) -> Result<AuditEntry, AuditError> {
        if self.is_broken.load(Ordering::Relaxed) {
            return Err(AuditError::IoError(std::io::Error::new(
                std::io::ErrorKind::Other,
                "Audit log is in a broken state (prior disk / fsync failure)",
            )));
        }

        // Compute params_hash over canonical JSON of the arguments.
        let params_hash = params.as_ref().map(|p| {
            use sha2::{Digest, Sha256};
            let canonical = canonical_json(p);
            let mut hasher = Sha256::new();
            hasher.update(canonical.as_bytes());
            hex::encode(hasher.finalize())
        });

        let (ack_tx, ack_rx) = oneshot::channel();

        let req = EntryRequest {
            session_id:     session_id.to_string(),
            event:          event.to_string(),
            tool_name:      tool_name.to_string(),
            params_hash,
            params,
            reason,
            latency_ms,
            identity_sub,
            identity_email,
            policy_hash,
            request_ip,
            ack:            ack_tx,
        };

        if self.sender.send(req).is_err() {
            self.is_broken.store(true, Ordering::Relaxed);
            return Err(AuditError::WriterDead);
        }

        // Block until fsync confirmed — this is the NFR-204 guarantee.
        let result = if tokio::runtime::Handle::try_current().is_ok() {
            tokio::task::block_in_place(|| ack_rx.blocking_recv())
        } else {
            ack_rx.blocking_recv()
        };

        match result {
            Ok(Ok(entry)) => Ok(entry),
            Ok(Err(e))    => Err(AuditError::SerializationError(e)),
            Err(_)        => {
                self.is_broken.store(true, Ordering::Relaxed);
                Err(AuditError::WriterDead)
            }
        }
    }

    /// Number of entries written so far (approximate — updated after each fsync).
    pub fn entry_count(&self) -> u64 {
        self.entry_count.load(Ordering::Relaxed)
    }

    /// True if a prior write or fsync error has rendered the logger unusable.
    pub fn is_broken(&self) -> bool {
        self.is_broken.load(Ordering::Relaxed)
    }
}

/// Produce a canonical JSON string with sorted object keys for deterministic hashing.
fn canonical_json(value: &Value) -> String {
    match value {
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            let entries: Vec<String> = keys
                .iter()
                .map(|k| format!("{:?}:{}", k, canonical_json(&map[*k])))
                .collect();
            format!("{{{}}}", entries.join(","))
        }
        Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(canonical_json).collect();
            format!("[{}]", items.join(","))
        }
        _ => value.to_string(),
    }
}
