//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (matches controller-gen output for agentwall_types.go).
// Regenerate with: controller-gen object paths="./..."

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ── IdentityConfig ───────────────────────────────────────────────────────

func (in *IdentityConfig) DeepCopyInto(out *IdentityConfig) {
	*out = *in
}

func (in *IdentityConfig) DeepCopy() *IdentityConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// ── NetworkPolicyConfig ──────────────────────────────────────────────────

func (in *NetworkPolicyConfig) DeepCopyInto(out *NetworkPolicyConfig) {
	*out = *in
	if in.AgentPodSelector != nil {
		in, out := &in.AgentPodSelector, &out.AgentPodSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GatewayPodSelector != nil {
		in, out := &in.GatewayPodSelector, &out.GatewayPodSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *NetworkPolicyConfig) DeepCopy() *NetworkPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// ── AgentWallPolicySpec ──────────────────────────────────────────────────

func (in *AgentWallPolicySpec) DeepCopyInto(out *AgentWallPolicySpec) {
	*out = *in
	out.Identity = in.Identity
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
}

func (in *AgentWallPolicySpec) DeepCopy() *AgentWallPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentWallPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// ── AgentWallPolicyStatus ────────────────────────────────────────────────

func (in *AgentWallPolicyStatus) DeepCopyInto(out *AgentWallPolicyStatus) {
	*out = *in
}

func (in *AgentWallPolicyStatus) DeepCopy() *AgentWallPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AgentWallPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// ── AgentWallPolicy ──────────────────────────────────────────────────────

func (in *AgentWallPolicy) DeepCopyInto(out *AgentWallPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *AgentWallPolicy) DeepCopy() *AgentWallPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentWallPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentWallPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── AgentWallPolicyList ──────────────────────────────────────────────────

func (in *AgentWallPolicyList) DeepCopyInto(out *AgentWallPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentWallPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AgentWallPolicyList) DeepCopy() *AgentWallPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentWallPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentWallPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}