apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentwall-operator
  namespace: agentwall-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentwall-operator-role
rules:
- apiGroups:
  - agentwall.io
  resources:
  - agentwallpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentwall.io
  resources:
  - agentwallpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agentwall-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agentwall-operator-role
subjects:
- kind: ServiceAccount
  name: agentwall-operator
  namespace: agentwall-system
