//! FR-3 / FR-4 stub: Policy YAML generation from observed SQLite events.
//!
//! Reads all observed tool call events from the DB and produces a valid
//! `agentwall-policy.yaml` draft that passes `agentwall lint`.
//!
//! This is a lightweight stub that satisfies AC-3.4. A richer implementation
//! (FR-4: Auto-Policy Generation) will replace this in Weeks 3-4.

use std::collections::{HashMap, HashSet};

use crate::proxy::db::Event;

/// Risk tier classification for a tool based on its name.
fn classify_risk_tier(tool_name: &str) -> &'static str {
    let lower = tool_name.to_lowercase();
    if lower.contains("delete")
        || lower.contains("drop")
        || lower.contains("wipe")
        || lower.contains("rm")
        || lower.contains("remove")
        || lower.contains("execute")
        || lower.contains("bash")
        || lower.contains("shell")
        || lower.contains("exec")
    {
        return "TIER_1";
    }
    if lower.contains("write")
        || lower.contains("insert")
        || lower.contains("update")
        || lower.contains("send")
        || lower.contains("post")
        || lower.contains("query")
        || lower.contains("database")
        || lower.contains("email")
        || lower.contains("message")
    {
        return "TIER_2";
    }
    "TIER_3"
}

/// Infer JSON type string from a `serde_json::Value`.
fn json_type_name(v: &serde_json::Value) -> &'static str {
    match v {
        serde_json::Value::Null => "null",
        serde_json::Value::Bool(_) => "boolean",
        serde_json::Value::Number(n) => {
            if n.is_f64() { "number" } else { "integer" }
        }
        serde_json::Value::String(_) => "string",
        serde_json::Value::Array(_) => "array",
        serde_json::Value::Object(_) => "object",
    }
}

/// Aggregate per-tool parameter metadata from a slice of events.
struct ParamMeta {
    types: HashSet<String>,
    max_len: usize,
    count: usize,
}

/// Generate a YAML policy draft from the observed events.
///
/// Produces a valid policy that passes `agentwall lint` (exit code 0).
/// Every observed tool is allowlisted with inferred parameter constraints.
pub fn generate_from_events(events: &[Event]) -> String {
    if events.is_empty() {
        return "# Auto-generated by AgentWall\n# No tool calls observed yet.\nversion: \"2\"\ndefault_action: deny\ntools: []\n".to_string();
    }

    // Group events by tool name
    let mut tool_map: HashMap<String, Vec<&Event>> = HashMap::new();
    for e in events {
        tool_map.entry(e.tool_name.clone()).or_default().push(e);
    }

    let observation_count = events.len();
    let tool_count = tool_map.len();

    // Build YAML header
    let mut out = format!(
        "# Auto-generated by AgentWall from {} observed tool calls\n\
         # Tools observed: {}\n\
         # Review this policy carefully before enabling enforcement.\n\
         # Run: agentwall lint agentwall-policy.yaml\n\n\
         version: \"2\"\n\
         default_action: deny\n\n\
         tools:\n",
        observation_count, tool_count
    );

    let mut sorted_tools: Vec<&String> = tool_map.keys().collect();
    sorted_tools.sort();

    for tool_name in sorted_tools {
        let tool_events = &tool_map[tool_name];
        let call_count = tool_events.len();
        let confidence = if call_count >= 50 {
            "high"
        } else if call_count >= 10 {
            "medium"
        } else {
            "low"
        };
        let risk_tier = classify_risk_tier(tool_name);

        // Collect parameter metadata
        let mut param_meta: HashMap<String, ParamMeta> = HashMap::new();
        for event in tool_events.iter() {
            if let Ok(params) = serde_json::from_str::<serde_json::Value>(&event.parameters) {
                if let Some(obj) = params.as_object() {
                    for (key, val) in obj {
                        let meta = param_meta.entry(key.clone()).or_insert(ParamMeta {
                            types: HashSet::new(),
                            max_len: 0,
                            count: 0,
                        });
                        meta.count += 1;
                        meta.types.insert(json_type_name(val).to_string());
                        if let Some(s) = val.as_str() {
                            let padded = ((s.len() as f64) * 1.2) as usize;
                            meta.max_len = meta.max_len.max(padded.max(64));
                        }
                    }
                }
            }
        }

        out.push_str(&format!(
            "  - name: {}\n\
             \x20   action: allow\n\
             \x20   risk_tier: {}\n\
             \x20   confidence: {}  # {} observations\n",
            tool_name, risk_tier, confidence, call_count
        ));

        if !param_meta.is_empty() {
            out.push_str("    parameters:\n");
            let mut sorted_params: Vec<&String> = param_meta.keys().collect();
            sorted_params.sort();
            for param_name in sorted_params {
                let meta = &param_meta[param_name];
                let inferred_type = if meta.types.len() == 1 {
                    meta.types.iter().next().unwrap().as_str().to_string()
                } else {
                    "string".to_string()
                };
                out.push_str(&format!(
                    "      - name: {}\n\
                     \x20       type: {}\n\
                     \x20       required: true\n",
                    param_name, inferred_type
                ));
                if inferred_type == "string" && meta.max_len > 0 {
                    out.push_str(&format!(
                        "        max_length: {}\n",
                        meta.max_len
                    ));
                }
            }
        }

        out.push('\n');
    }

    out
}
